services:

  application:
    build: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/product_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PASSWORD=123
      - SPRING_DATA_REDIS_PORT=6379
      - MINIO.URL=http://minio:9000
      - MINIO_ACCESS_KEY=appstorage
      - MINIO_SECRET_KEY=appstorage
    depends_on:
      - db
      - redis
      - minio

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=123
      - REDIS_PORT=6379

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'product_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    restart: always
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: appstorage
      MINIO_ROOT_PASSWORD: appstorage
      MINIO_DEFAULT_BUCKETS: user-files
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  redis-data:
  mysql-data:
  minio-data: