version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - my-db:/var/lib/redis
    environment:
      - REDIS_PASSWORD=123
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  minio:
    restart: always
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: user-files
    volumes:
     - my-db:/var/lib/minio:/data
    command: server /data --console-address ":9001"
# Names our volume
volumes:
  my-db: